"""Prometheus metrics exporter for the IceStream Event Generator."""

import logging
from typing import Dict, Optional
from prometheus_client import Counter, Gauge, Histogram, start_http_server

logger = logging.getLogger(__name__)

# Prometheus Metrics Definitions for Generator
EVENTS_GENERATED_TOTAL = Counter(
    "icestream_events_generated_total",
    "Total number of events generated by the engine",
)

EVENTS_PUBLISHED_TOTAL = Counter(
    "icestream_events_published_total",
    "Total number of events successfully acknowledged by Kafka",
)

PUBLISH_FAILURES_TOTAL = Counter(
    "icestream_publish_failures_total",
    "Total number of events that failed Kafka delivery",
)

PRODUCER_EVENTS_PER_SECOND = Gauge(
    "icestream_producer_events_per_second",
    "Current publishing rate in events per second",
)

PRODUCER_LATENCY_SECONDS = Histogram(
    "icestream_producer_latency_seconds",
    "Kafka producer delivery acknowledgment latency in seconds",
    buckets=(0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5),
)

FAULTS_INJECTED_TOTAL = Counter(
    "icestream_faults_injected_total",
    "Total number of faults injected into the event stream",
    labelnames=["fault_type"],
)

_METRICS_SERVER_STARTED = False


def start_generator_metrics_server(port: int = 8000) -> bool:
    """Start the Prometheus metrics HTTP server for the generator."""
    global _METRICS_SERVER_STARTED
    if _METRICS_SERVER_STARTED:
        return True

    try:
        start_http_server(port)
        _METRICS_SERVER_STARTED = True
        logger.info(f"Prometheus generator metrics server started on port {port}")
        return True
    except Exception as e:
        logger.warning(f"Failed to start generator metrics server on port {port}: {e}")
        return False


class GeneratorMetricsTracker:
    """Helper tracker to record generator performance metrics to Prometheus."""

    @staticmethod
    def record_generated():
        EVENTS_GENERATED_TOTAL.inc()

    @staticmethod
    def record_published(latency_sec: Optional[float] = None):
        EVENTS_PUBLISHED_TOTAL.inc()
        if latency_sec is not None and latency_sec >= 0:
            PRODUCER_LATENCY_SECONDS.observe(latency_sec)

    @staticmethod
    def record_failure():
        PUBLISH_FAILURES_TOTAL.inc()

    @staticmethod
    def update_producer_rate(rate: float):
        PRODUCER_EVENTS_PER_SECOND.set(rate)

    @staticmethod
    def record_fault(fault_type: str):
        FAULTS_INJECTED_TOTAL.labels(fault_type=fault_type).inc()
