# Prometheus Configuration for IceStream Infrastructure
global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'icestream-backend'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['icestream-backend:8000']

  - job_name: 'flink-jobmanager'
    metrics_path: '/v1/overview'
    static_configs:
      - targets: ['icestream-flink-jobmanager:8081']

  - job_name: 'grafana'
    static_configs:
      - targets: ['icestream-grafana:3000']
